### PR TITLE
DEV-13378-Terraform-Repo-for-EMR-hbase

### PR DESCRIPTION
**Pull request by jaynathani-tamr**
- All the sub modules are updated and the root module is knitted to work together with all the sub modules.
- A complete working example is also provided in the `/examples` directory.
- The readme of the root module contains all the variables that can be set, required and optional. It also provides a list of all the outputs that can be expected out of the module.

To-do task once the PR will be ready to merged:
- Change source in the examples of all the sub modules and the root module.
- Change the variables mentioned in the tfvars file (the current ones are from our EMR Dev environment)

### CODE REVIEW

**Review by souza-dan — COMMENTED** [review]
Overall looks good. Maybe we should take out the real values though.

**Review by cbelitz — COMMENTED** [review]
generally looks good to me. agree with Nick's comment about the sg_rules local variable

**Review by cbelitz — APPROVED** [review]
One small clarifying comment but looks good. Thanks for making the changes

**Review by souza-dan — APPROVED** [review]
LGTM

**Pull request merged**
