### PR TITLE
[CA-10] tag based authorization

### PR DESCRIPTION
**Pull request by fvazquez-caylent**
To allow for further tightening of IAM permissions, the EMR module should allow users to set tags that will be applied to the EMR cluster and every resource created because of EMR.

Summary of changes:

Add new variable tags.
Add deprecation notice for additional_tags, update descriptions to keep consistency across modules.
Create Examples/Minimal with exampled tags.

### CODE REVIEW

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Review by souza-dan — COMMENTED** [review]
Pattern looks good, I think you just need to rebase.

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Review by souza-dan — APPROVED** [review]
LGTM, great to see everything getting tagged!

**Pull request merged**
