### PR TITLE
DEV-13732 DEV-13643 tags for emrfs dynamodb

### PR DESCRIPTION
**Pull request by jaynathani-tamr**
Blocker requirement from Transamerica to have tags everywhere. 

This code change adds creation of 3 more resources as part of the module:
1. EMRFS Dynamodb table (can now be controlled by the terraform module, previously was controlled by EMR)
2. static_time - for current timestamp
3. Dynamodb table item (replicating the one that EMR creates)

This ticket was just to add tags to the dynamodb resource that gets created through EMR, but as we did not have state for it in our terraform, this ticket also includes changing that structure into creating the dynamodb table through the terraform module and add tags.

NOTE: Right now we have a work around (aws cli command) for creating the dynamodb table item because the AWS Provider creates the item and throws an error and causes the state to go out of sync. More info on that here: https://github.com/terraform-providers/terraform-provider-aws/issues/12545

P.S.: Once the PR gets approved, I will create a tag and change the example values.

Also, as we have the state of the dynamodb resources created now, we would be able to delete it when running `terraform destroy`. Basically, it also resolves the ticket: https://datatamr.atlassian.net/browse/DEV-13643

### CODE REVIEW

**Review by laferrieren — COMMENTED** [review]
can you also run terraform fmt

**Review by souza-dan — COMMENTED** [review]
Approach is really solid, just need to do the cleanup of tamr specific stuff, changelog, bump the version, etc.

**Review by souza-dan — COMMENTED** [review]
Looks great!

All that's left is to increment the version and the tag in the example:
https://github.com/jaynathani-tamr/terraform-emr-hbase/blob/DEV-13732-tags-for-emrfs-dynamodb/VERSION

https://github.com/jaynathani-tamr/terraform-emr-hbase/blob/DEV-13732-tags-for-emrfs-dynamodb/README.md#example

**Review by cbelitz — COMMENTED** [review]
looks good to me once the git history is cleaned!

**Review by cbelitz — COMMENTED** [review]
looks good! just wondering about the version bump

**Review by souza-dan — APPROVED** [review]
LGTM, I agree with @cbelitz that this could be `0.2.0`.

**Pull request merged**
