### PR TITLE
DEV-14295 - Updates minimum provider version

### PR DESCRIPTION
**Pull request by souza-dan**
https://datatamr.atlassian.net/browse/DEV-14295

Ran plan for all the examples.

Ran into this issue when `custom_ami_id` was not set:
```
Error: "custom_ami_id" must begin with 'ami-' and be comprised of only [a-z0-9]: 

  on ../../modules/aws-emr-cluster/main.tf line 67, in resource "aws_emr_cluster" "emr-cluster":
  67:   custom_ami_id = var.custom_ami_id
```

### CODE REVIEW

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Review by daniosim — APPROVED** [review]
👍 and nice catch!

**Pull request merged**
