### PR TITLE
DEV-14723 - Support for specifying bid prices

### PR DESCRIPTION
**Pull request by souza-dan**
Depends on: https://github.com/Datatamer/terraform-aws-emr/pull/37

https://datatamr.atlassian.net/browse/DEV-14723

Tried a deployment with both master and core bid price set:
Screen Shot 2021-04-06 at 5 57 23 PM

### CODE REVIEW

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Review by daniosim — APPROVED** [review]
👍

**Pull request merged**
