### PR TITLE
DEV-14276, DEV-14294 Consistent READMEs and add required_providers

### PR DESCRIPTION
**Pull request by daniosim**
[DEV-14294](https://datatamr.atlassian.net/browse/DEV-14294) - Add required_providers to AWS repos
[DEV-14276](https://datatamr.atlassian.net/browse/DEV-14276) - Make READMEs consistent

### CODE REVIEW

**Review by souza-dan — COMMENTED** [review]
Huge improvement! Couple super minor things but otherwise looks great!

**Review by jaynathani-tamr — APPROVED** [review]
LGTM

**Review by souza-dan — APPROVED** [review]
LGTM

**Pull request merged**
