### PR TITLE
DEV-14765 Upgrade and pin terraform-aws-modules/key-pair/aws

### PR DESCRIPTION
**Pull request by daniosim**
https://datatamr.atlassian.net/browse/DEV-14765

### CODE REVIEW

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Review by aditimarkale — APPROVED** [review]

**Review by souza-dan — APPROVED** [review]
LGTM

**Pull request merged**
